matrix:
  include:
    - language: c
      compiler: clang
      before_script:
        - cd c
      script:
        - make

    - language: cpp
      compiler: clang
      before_script:
        - cd cpp
      script:
        - make

    - language: rust
      before_script:
        - cd rust
    
    - language: java
      before_script:
        - cd java

    - language: python
      python: 3.6
      before_script:
        - cd python
      install:
        - echo "Hello ma!"
      script:
        - python cards.py
    
    - language: swift
      os: osx
      osx_image: xcode9.3
      before_script:
        - cd swift
      script:
        - swift build
    
    - language: node_js
      before_script:
        - cd nodejs

    - language: objective-c
      os: osx
      osx_image: xcode9.3
      before_script:
        - cd objc
      install: true
      script:
        - xcodebuild -project Cards.xcodeproj -scheme Cards build
        - xcodebuild -project Cards.xcodeproj -scheme Cards test